### ISSUE TITLE
Errors trying to build the latest version (1.1.2) on GNU/Linux

### ISSUE THREAD

**Issue by vanfanel** [Rubberduckycooly/Sonic-CD-11-Decompilation#116]
Hi,

After some months, I have tried to build the latest "stable version" and it won't link.
Previous versions built with no problems at all.

This is what gcc is saying:

```
g++ -MMD -MP -MF objects/.d -D_REENTRANT -I/usr/local/include/SDL2  -Idependencies/all/filesystem/include -Idependencies/all/theoraplay -Idependencies/all/upng  objects/dependencies/all/theoraplay/theoraplay.c.o objects/RSDKv3/Animation.cpp.o objects/RSDKv3/Audio.cpp.o objects/RSDKv3/Collision.cpp.o objects/RSDKv3/Debug.cpp.o objects/RSDKv3/Drawing.cpp.o objects/RSDKv3/Ini.cpp.o objects/RSDKv3/Input.cpp.o objects/RSDKv3/main.cpp.o objects/RSDKv3/Math.cpp.o objects/RSDKv3/Object.cpp.o objects/RSDKv3/Palette.cpp.o objects/RSDKv3/Player.cpp.o objects/RSDKv3/Reader.cpp.o objects/RSDKv3/RetroEngine.cpp.o objects/RSDKv3/Scene.cpp.o objects/RSDKv3/Scene3D.cpp.o objects/RSDKv3/Script.cpp.o objects/RSDKv3/Sprite.cpp.o objects/RSDKv3/String.cpp.o objects/RSDKv3/Text.cpp.o objects/RSDKv3/Userdata.cpp.o objects/RSDKv3/Video.cpp.o -o bin/soniccd -L/usr/local/lib -Wl,-rpath,/usr/local/lib -Wl,--enable-new-dtags -lSDL2 -lvorbisfile -lvorbis -ltheoradec -logg -pthread 
/usr/bin/ld: objects/RSDKv3/Userdata.cpp.o: in function `initMods()':
Userdata.cpp:(.text+0x2ddc): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: Userdata.cpp:(.text+0x3364): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x339c): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x33c8): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::operator*() const'
/usr/bin/ld: Userdata.cpp:(.text+0x36b4): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::operator++()'
/usr/bin/ld: Userdata.cpp:(.text+0x36c4): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x36d0): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x36dc): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x37b0): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x37e8): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x3814): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::operator*() const'
/usr/bin/ld: Userdata.cpp:(.text+0x3b00): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::operator++()'
/usr/bin/ld: Userdata.cpp:(.text+0x3b10): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x3b1c): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x3b28): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x3bf0): undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: Userdata.cpp:(.text+0x3d08): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x3d1c): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x3d2c): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x3d90): undefined reference to `std::filesystem::__cxx11::filesystem_error::~filesystem_error()'
/usr/bin/ld: Userdata.cpp:(.text+0x3da8): undefined reference to `std::filesystem::__cxx11::filesystem_error::~filesystem_error()'
/usr/bin/ld: Userdata.cpp:(.text+0x3e54): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x3e68): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x3e78): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::~recursive_directory_iterator()'
/usr/bin/ld: Userdata.cpp:(.text+0x3edc): undefined reference to `std::filesystem::__cxx11::filesystem_error::~filesystem_error()'
/usr/bin/ld: Userdata.cpp:(.text+0x3ef4): undefined reference to `std::filesystem::__cxx11::filesystem_error::~filesystem_error()'
/usr/bin/ld: Userdata.cpp:(.text+0x4004): undefined reference to `std::filesystem::__cxx11::filesystem_error::~filesystem_error()'
/usr/bin/ld: Userdata.cpp:(.text+0x4018): undefined reference to `std::filesystem::__cxx11::filesystem_error::~filesystem_error()'
/usr/bin/ld: objects/RSDKv3/Userdata.cpp.o: in function `std::filesystem::__cxx11::path::path(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::filesystem::__cxx11::path::format)':
Userdata.cpp:(.text._ZNSt10filesystem7__cxx114pathC2EONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS1_6formatE[_ZNSt10filesystem7__cxx114pathC5EONSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS1_6formatE]+0x4c): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: objects/RSDKv3/Userdata.cpp.o: in function `std::filesystem::__cxx11::directory_entry::status() const':
Userdata.cpp:(.text._ZNKSt10filesystem7__cxx1115directory_entry6statusEv[_ZNKSt10filesystem7__cxx1115directory_entry6statusEv]+0x10): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: objects/RSDKv3/Userdata.cpp.o: in function `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&)':
Userdata.cpp:(.text._ZNSt10filesystem7__cxx1118directory_iteratorC2ERKNS0_4pathE[_ZNSt10filesystem7__cxx1118directory_iteratorC5ERKNS0_4pathE]+0x20): undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: objects/RSDKv3/Userdata.cpp.o: in function `std::filesystem::__cxx11::recursive_directory_iterator::recursive_directory_iterator(std::filesystem::__cxx11::path const&)':
Userdata.cpp:(.text._ZNSt10filesystem7__cxx1128recursive_directory_iteratorC2ERKNS0_4pathE[_ZNSt10filesystem7__cxx1128recursive_directory_iteratorC5ERKNS0_4pathE]+0x20): undefined reference to `std::filesystem::__cxx11::recursive_directory_iterator::recursive_directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: objects/RSDKv3/Userdata.cpp.o: in function `std::filesystem::exists(std::filesystem::__cxx11::path const&)':
Userdata.cpp:(.text._ZNSt10filesystem6existsERKNS_7__cxx114pathE[_ZNSt10filesystem6existsERKNS_7__cxx114pathE]+0x10): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: objects/RSDKv3/Userdata.cpp.o: in function `std::filesystem::is_directory(std::filesystem::__cxx11::path const&)':
Userdata.cpp:(.text._ZNSt10filesystem12is_directoryERKNS_7__cxx114pathE[_ZNSt10filesystem12is_directoryERKNS_7__cxx114pathE]+0x10): undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: objects/RSDKv3/Userdata.cpp.o: in function `std::filesystem::__cxx11::filesystem_error::filesystem_error(std::filesystem::__cxx11::filesystem_error const&)':
Userdata.cpp:(.text._ZNSt10filesystem7__cxx1116filesystem_errorC2ERKS1_[_ZNSt10filesystem7__cxx1116filesystem_errorC5ERKS1_]+0x20): undefined reference to `vtable for std::filesystem::__cxx11::filesystem_error'
/usr/bin/ld: Userdata.cpp:(.text._ZNSt10filesystem7__cxx1116filesystem_errorC2ERKS1_[_ZNSt10filesystem7__cxx1116filesystem_errorC5ERKS1_]+0x24): undefined reference to `vtable for std::filesystem::__cxx11::filesystem_error'
/usr/bin/ld: objects/RSDKv3/Userdata.cpp.o: in function `std::filesystem::__cxx11::path::path<char [256], std::filesystem::__cxx11::path>(char const (&) [256], std::filesystem::__cxx11::path::format)':
Userdata.cpp:(.text._ZNSt10filesystem7__cxx114pathC2IA256_cS1_EERKT_NS1_6formatE[_ZNSt10filesystem7__cxx114pathC5IA256_cS1_EERKT_NS1_6formatE]+0x5c): undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: objects/RSDKv3/Userdata.cpp.o:(.data.rel.local.DW.ref._ZTINSt10filesystem7__cxx1116filesystem_errorE[DW.ref._ZTINSt10filesystem7__cxx1116filesystem_errorE]+0x0): undefined reference to `typeinfo for std::filesystem::__cxx11::filesystem_error'
collect2: error: ld returned 1 exit status
make: *** [Makefile:62: bin/soniccd] Error 1
```

Any ideas on what could be going on here?

Thanks!

PD: The same errors are happening with the Sonic-1-2-2013 decompilation now...

**Comment by vanfanel** [comment]
Seems to build fine with gcc 9.3, but current stable DEBIAN uses gcc 8.3, so that's why it fails to build on my Debian system.

So, the problem is with the mod filesystem support code, which only builds on gcc 9.3 and not with gcc 8.3. But gcc 8.3 is VERY widely used on stable Debian.

**Comment by dilworks** [comment]
Can confirm here on both projects - Debian Stable uses 8.3, and while next Debian release is scheduled to ship with GCC 10 (hopefully sometime later this year), they usually don't backport newer compilers to older releases.

**Comment by shantigilbert** [comment]
I fixed it by adding `-lstdc++fs`

`sed -i "s|pthread|pthread -lstdc++fs|" Makefile`

**Comment by dilworks** [comment]
Can confirm @shantigilbert fix works on GCC 8.3, thanks for it!

**Comment by vanfanel** [comment]
I can also confirm that @shantigilbert fix makes the game build with GCC 8.3 on Debian stable.
Maybe it should be added to the default flags?

**Comment by Leonx254** [comment]
Do you still have a problem building in the latest commits?

**Comment by dilworks** [comment]
> Do you still have a problem building in the latest commits?

Yes, -lstdc++fs is still required for older GCC versions. And a workaround is now needed too for the new tinyxml2 dependency, as I was getting errors there too (because it couldn't find tinyxml2.h despite being there!). I managed to build with the following command:

`make CXXFLAGS="-O2 -Idependencies/all/tinyxml2/" LIBS=-lstdc++fs -j4`

Newer GCC versions will not require -lstdc++fs, but GCC 8.x certainly does. Yeah, I know that Debian 10 is now old news and I'll eventually update this machine. But not today. And the built executable still works just fine anyway.

**Comment by Leonx254** [comment]
Updated the readme to awknowledge this, along with how to set up tinyxml2 to avoid package issues
