### ISSUE TITLE
Fails to compile when RETRO_USE_HW_RENDER=OFF

### ISSUE THREAD

**Issue by GiantBlargg** [Rubberduckycooly/Sonic-CD-11-Decompilation#274]
### Before opening this issue, I ensure that...

- [x] I have read the [FAQ](https://github.com/RSDKModding/RSDKv3-Decompilation/blob/main/FAQ.md) and confirmed my issue is not mentioned in it.
- [x] I have checked **both open and closed** issues and confirmed this bug has not already been reported.
- [x] I am not asking for tech support (e.g. game closing on startup, error when trying to build, etc).
- [x] I am not asking for modding support or reporting a bug in a specific mod; this bug either occurs without mods enabled or is directly related to the mod loader.
- [x] This bug is not related to any unofficial fork/port of the decompilation, and any issues with those should be kept in the appropriate repository.

### Expected Behavior

Project compiles

### Actual Behavior

It fails to build (I promise this is a real error, not tech support; see details at bottom; this form seems ill suited to report build issues)

### Steps to Reproduce

```
$ git clone https://github.com/RSDKModding/RSDKv3-Decompilation.git --recursive
$ cd RSDKv3-Decompilation
$ cmake -B build -DCMAKE_BUILD_TYPE=Release -DRETRO_USE_HW_RENDER=OFF
$ cmake --build build --config release
```

### Log File

Build log:
```
$ cmake -B build -DCMAKE_BUILD_TYPE=Release -DRETRO_USE_HW_RENDER=OFF
-- The C compiler identification is GNU 16.2.1
-- The CXX compiler identification is GNU 16.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "3.0.5")
-- Checking for module 'ogg'
--   Found ogg, version 1.3.6
found libogg
-- Checking for modules 'theora;theoradec'
--   Found theora, version 1.2.0
--   Found theoradec, version 1.2.0
found libtheora
-- Checking for modules 'vorbis;vorbisfile'
--   Found vorbis, version 1.3.7
--   Found vorbisfile, version 1.3.7
found libvorbis
-- Checking for module 'sdl2'
--   Found sdl2, version 2.32.70
-- Configuring done (0.8s)
-- Generating done (0.0s)
-- Build files have been written to: /tmp/RSDKv3-Decompilation/build

$ cmake --build build --config release
[  3%] Building CXX object CMakeFiles/RetroEngine.dir/dependencies/all/tinyxml2/tinyxml2.cpp.o
[  7%] Building C object CMakeFiles/RetroEngine.dir/dependencies/all/theoraplay/theoraplay.c.o
[ 11%] Building CXX object CMakeFiles/RetroEngine.dir/RSDKv3/Animation.cpp.o
[ 14%] Building CXX object CMakeFiles/RetroEngine.dir/RSDKv3/Audio.cpp.o
[ 18%] Building CXX object CMakeFiles/RetroEngine.dir/RSDKv3/Collision.cpp.o
[ 22%] Building CXX object CMakeFiles/RetroEngine.dir/RSDKv3/Debug.cpp.o
[ 25%] Building CXX object CMakeFiles/RetroEngine.dir/RSDKv3/Drawing.cpp.o
/tmp/RSDKv3-Decompilation/RSDKv3/Drawing.cpp: In function ‘void SetScreenDimensions(int, int, int, int)’:
/tmp/RSDKv3-Decompilation/RSDKv3/Drawing.cpp:1409:58: error: ‘bufferW’ was not declared in this scope
 1409 |     float scaleW = (float)HW_TEXTURE_SIZE / (float)(1 << bufferW);
      |                                                          ^~~~~~~
make[2]: *** [CMakeFiles/RetroEngine.dir/build.make:163: CMakeFiles/RetroEngine.dir/RSDKv3/Drawing.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/RetroEngine.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

```

### Decompilation Version

e81dc03

### Game Version

Mobile (Sega Forever)

### Game Revision

N/A

### Renderer Type

Software Renderer

### Platform

Linux

### Additional Comments

The error was introduced in 55bd4ca. I tried to leave a comment on the commit but it doesn't appear to be showing up.
https://github.com/RSDKModding/RSDKv3-Decompilation/blob/e81dc03a7cd99d2758dcdee436aa409f037f0652/RSDKv3/Drawing.cpp#L1409 `bufferW` is used here but is defined further up inside `#if RETRO_USING_OPENGL`. If OpenGL is disabled the bufferW is never defined so this line fails to compile.

**Comment by LittlePlanetCD** [comment]
should be fixed in a984027558f6cf98521d2261b770d5f69ef04dc5

I forgot that was under OpenGL, should be buildable now, though. just tested it and it was fine on my machine.
